# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [3]:
sinasc_raw = pd.read_csv('sinasc_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [4]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

In [5]:
def faixas(col:str, valor:float) -> None:

    condicao = sinasc_raw[col] <= valor

    df = sinasc_raw.groupby(by=condicao).mean()
    
    print('media')
    print(df['CONSULTAS'])
    print('\n')
    print(df['PARIDADE'])


    df = sinasc_raw.groupby(by=condicao).sum()

    print('soma')
    print(df['CONSULTAS'])
    print('\n')
    print(df['PARIDADE'])


    df = sinasc_raw.groupby(by=condicao).min()

    print('minimo')
    print(df['CONSULTAS'])
    print('\n')
    print(df['PARIDADE'])


    df = sinasc_raw.groupby(by=condicao).max()

    print('maximo')
    print(df['CONSULTAS'])
    print('\n')
    print(df['PARIDADE'])


    df = sinasc_raw.groupby(by=condicao).median()

    print('mediana')
    print(df['CONSULTAS'])
    print('\n')
    print(df['PARIDADE'])


    df = sinasc_raw.groupby(by=condicao).std()

    print('std')
    print(df['CONSULTAS'])
    print('\n')
    print(df['PARIDADE'])
    
    return None

# Tarefa 2

### 1. Crie 2 faixas de Latitude do município (munResLat) sendo uma acima e outra abaixo de -10.5 e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [6]:
faixas('munResLat', -10.5)

/tmp/ipykernel_66752/3103490778.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).mean()
/tmp/ipykernel_66752/3103490778.py:13: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).sum()
/tmp/ipykernel_66752/3103490778.py:21: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).min()

media
munResLat
False    3.467260
True     3.694297
Name: CONSULTAS, dtype: float64


munResLat
False    0.646170
True     0.651582
Name: PARIDADE, dtype: float64
soma
munResLat
False    48663
True     48000
Name: CONSULTAS, dtype: int64


munResLat
False    9069
True     8466
Name: PARIDADE, dtype: int64
minimo
munResLat
False    1
True     1
Name: CONSULTAS, dtype: int64


munResLat
False    0
True     0
Name: PARIDADE, dtype: int64
maximo
munResLat
False    9
True     9
Name: CONSULTAS, dtype: int64


munResLat
False    1
True     1
Name: PARIDADE, dtype: int64
mediana
munResLat
False    4.0
True     4.0
Name: CONSULTAS, dtype: float64


munResLat
False    1.0
True     1.0
Name: PARIDADE, dtype: float64
std
munResLat
False    0.888452
True     0.643372
Name: CONSULTAS, dtype: float64


munResLat
False    0.478174
True     0.476488
Name: PARIDADE, dtype: float64

/tmp/ipykernel_66752/3103490778.py:29: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).max()
/tmp/ipykernel_66752/3103490778.py:37: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).median()
/tmp/ipykernel_66752/3103490778.py:45: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).std()

### 2. Crie 2 faixas da área dos municípios (munResArea) sendo uma acima e outra abaixo de 3000 e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [7]:
faixas('munResArea', 3000)

/tmp/ipykernel_66752/3103490778.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).mean()
/tmp/ipykernel_66752/3103490778.py:13: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).sum()
/tmp/ipykernel_66752/3103490778.py:21: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).min()

media
munResArea
False    3.537209
True     3.740180
Name: CONSULTAS, dtype: float64


munResArea
False    0.649869
True     0.644185
Name: PARIDADE, dtype: float64
soma
munResArea
False    77143
True     19520
Name: CONSULTAS, dtype: int64


munResArea
False    14173
True      3362
Name: PARIDADE, dtype: int64
minimo
munResArea
False    1
True     1
Name: CONSULTAS, dtype: int64


munResArea
False    0
True     0
Name: PARIDADE, dtype: int64
maximo
munResArea
False    9
True     9
Name: CONSULTAS, dtype: int64


munResArea
False    1
True     1
Name: PARIDADE, dtype: int64
mediana
munResArea
False    4.0
True     4.0
Name: CONSULTAS, dtype: float64


munResArea
False    1.0
True     1.0
Name: PARIDADE, dtype: float64
std
munResArea
False    0.821128
True     0.607492
Name: CONSULTAS, dtype: float64


munResArea
False    0.477022
True     0.478805
Name: PARIDADE, dtype: float64

/tmp/ipykernel_66752/3103490778.py:29: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).max()
/tmp/ipykernel_66752/3103490778.py:37: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).median()
/tmp/ipykernel_66752/3103490778.py:45: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).std()

### 3. Determine faixas na variável munResAlt e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [8]:
faixas('munResAlt', 153.0)

/tmp/ipykernel_66752/3103490778.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).mean()
/tmp/ipykernel_66752/3103490778.py:13: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).sum()

media
munResAlt
False    3.735939
True     3.419395
Name: CONSULTAS, dtype: float64


munResAlt
False    0.645606
True     0.651887
Name: PARIDADE, dtype: float64
soma
munResAlt
False    50084
True     46579
Name: CONSULTAS, dtype: int64


munResAlt
False    8655
True     8880
Name: PARIDADE, dtype: int64

/tmp/ipykernel_66752/3103490778.py:21: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).min()

minimo
munResAlt
False    1
True     1
Name: CONSULTAS, dtype: int64


munResAlt
False    0
True     0
Name: PARIDADE, dtype: int64
maximo
munResAlt
False    9
True     9
Name: CONSULTAS, dtype: int64


munResAlt
False    1
True     1
Name: PARIDADE, dtype: int64
mediana
munResAlt
False    4.0
True     4.0
Name: CONSULTAS, dtype: float64


munResAlt
False    1.0
True     1.0
Name: PARIDADE, dtype: float64
std
munResAlt
False    0.600337
True     0.910623
Name: CONSULTAS, dtype: float64


munResAlt
False    0.478347
True     0.476390
Name: PARIDADE, dtype: float64

/tmp/ipykernel_66752/3103490778.py:29: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).max()
/tmp/ipykernel_66752/3103490778.py:37: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).median()
/tmp/ipykernel_66752/3103490778.py:45: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = sinasc_raw.groupby(by=condicao).std()

### 4. Plote no mesmo grafico ao longo do tempo a idade media das mulheres de cada regiao imediatas de rondonia
https://pt.wikipedia.org/wiki/Lista_de_regi%C3%B5es_geogr%C3%A1ficas_intermedi%C3%A1rias_e_imediatas_de_Rond%C3%B4nia

In [29]:
imediatas = {
    "Candeias do Jamari": "Porto Velho",
    "Guajará-Mirim": "Porto Velho",
    "Itapuã do Oeste": "Porto Velho",
    "Nova Mamoré": "Porto Velho",
    "Porto Velho": "Porto Velho",
    "Ariquemes": "Porto Velho",
    "Alto Paraíso": "Porto Velho",
    "Ariquemes": "Ariquemes",
    "Buritis": "Ariquemes",
    "Cacaulândia": "Ariquemes",
    "Campo Novo de Rondônia": "Ariquemes",
    "Cujubim": "Ariquemes",
    "Monte Negro": "Ariquemes",
    "Rio Crespo": "Ariquemes",
    "Jaru": "Jaru",
    "Governador Jorge Teixeira": "Jaru",
    "Machadinho D'Oeste": "Jaru",
    "Theobroma": "Jaru",
    "Vale do Anari": "Jaru",
    "Alvorada D'Oeste": "Ji-Paraná",
    "Costa Marques": "Ji-Paraná",
    "Ji-Paraná": "Ji-Paraná",
    "Mirante da Serra": "Ji-Paraná",
    "Nova União": "Ji-Paraná",
    "Ouro Preto do Oeste": "Ji-Paraná",
    "Presidente Médici": "Ji-Paraná",
    "São Francisco do Guaporé": "Ji-Paraná",
    "São Miguel do Guaporé": "Ji-Paraná",
    "Seringueiras": "Ji-Paraná",
    "Teixeirópolis": "Ji-Paraná",
    "Urupá": "Ji-Paraná",
    "Vale do Paraíso": "Ji-Paraná",
    "Cacoal": "Cacoal",
    "Alta Floresta D'Oeste": "Cacoal",
    "Alto Alegre dos Parecis": "Cacoal",
    "Castanheiras": "Cacoal",
    "Espigão D'Oeste": "Cacoal",
    "Ministro Andreazza": "Cacoal",
    "Nova Brasilândia D'Oeste": "Cacoal",
    "Novo Horizonte do Oeste": "Cacoal",
    "Parecis": "Cacoal",
    "Pimenta Bueno": "Cacoal",
    "Primavera de Rondônia": "Cacoal",
    "Rolim de Moura": "Cacoal",
    "Santa Luzia D'Oeste": "Cacoal",
    "São Felipe D'Oeste": "Cacoal",
    "Vilhena": "Vilhena",
    "Cabixi": "Vilhena",
    "Cerejeiras": "Vilhena",
    "Chupinguaia": "Vilhena",
    "Colorado do Oeste": "Vilhena",
    "Corumbiara": "Vilhena",
    "Pimenteiras do Oeste": "Vilhena"
}

In [28]:
'''
usa o df original com as colunas de interesse para selecionar por nome do munícipio, depois agrupar pela
classificação imediatas, e depois tira a média
'''

sinasc_raw[['IDADEMAE','munResNome']].set_index('munResNome').groupby(imediatas).mean().round(0)

             IDADEMAE
munResNome
Ariquemes        25.0
Cacoal           26.0
Jaru             26.0
Ji-Paraná        26.0
Porto Velho      26.0
Vilhena          26.0

### 5. Utilize a tabela do link abaixo e crie faixas utilizando o mapping e gere agrupamentos utilizando essas faixas como chave

### 5.1 IDH
A - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_IDH-M

In [34]:
# foram selecionados alguns municipios para a análise

IDH = {
    "Porto Velho": "IDH-M alto",
    "Guajará-Mirim": "IDH-M médio",
    "Nova Mamoré": "IDH-M baixo", 
    "Alto Paraíso": "IDH-M baixo",
    "Campo Novo de Rondônia": "IDH-M baixo",
    "Jaru": "IDH-M médio",
    "Governador Jorge Teixeira": "IDH-M baixo",
    "Machadinho D'Oeste": "IDH-M baixo",
    "Theobroma": "IDH-M baixo",
    "Vale do Anari": "IDH-M baixo",
    "Ji-Paraná": "IDH-M alto",
    "Nova União": "IDH-M baixo",
    "Ouro Preto do Oeste": "IDH-M médio",
    "Presidente Médici": "IDH-M médio",
    "Seringueiras": "IDH-M baixo",
    "Cacoal": "IDH-M alto",
    "Castanheiras": "IDH-M médio",
    "Espigão D'Oeste": "IDH-M médio",
    "Pimenta Bueno": "IDH-M alto",
    "Santa Luzia D'Oeste": "IDH-M médio",
    "Cerejeiras": "IDH-M médio",
    "Chupinguaia": "IDH-M médio",
    "Colorado do Oeste": "IDH-M médio",
    "Pimenteiras do Oeste": "IDH-M médio"
}

In [43]:
# calcula a idade média da mãe e do pai de acordo com o IDH

sinasc_raw[['IDADEMAE','IDADEPAI','munResNome']].set_index('munResNome').groupby(IDH).mean()

              IDADEMAE   IDADEPAI
munResNome
IDH-M alto   26.329606  31.088876
IDH-M baixo  25.322445  31.188088
IDH-M médio  26.085356  31.180353

### 5.2 IFDM 
B - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_IFDM

In [45]:
IFDM = {
    "Porto Velho": "Desenvolvimento Moderado",
    "Guajará-Mirim": "Desenvolvimento Regular",
    "Nova Mamoré": "Desenvolvimento Regular", 
    "Alto Paraíso": "Desenvolvimento Regular",
    "Campo Novo de Rondônia": "Desenvolvimento Regular",
    "Jaru": "Desenvolvimento Moderado",
    "Governador Jorge Teixeira": "Desenvolvimento Moderado",
    "Machadinho D'Oeste": "Desenvolvimento Moderado",
    "Theobroma": "Desenvolvimento Moderado",
    "Vale do Anari": "Desenvolvimento Regular",
    "Ji-Paraná": "Desenvolvimento Moderado",
    "Nova União": "Desenvolvimento Regular",
    "Ouro Preto do Oeste": "Desenvolvimento Moderado",
    "Presidente Médici": "Desenvolvimento Moderado",
    "Seringueiras": "Desenvolvimento Regular",
    "Cacoal": "Desenvolvimento Moderado",
    "Castanheiras": "Desenvolvimento Regular",
    "Espigão D'Oeste": "Desenvolvimento Regular",
    "Pimenta Bueno": "Desenvolvimento Moderado",
    "Santa Luzia D'Oeste": "Desenvolvimento Moderado",
    "Cerejeiras": "Desenvolvimento Moderado",
    "Chupinguaia": "Desenvolvimento Moderado",
    "Colorado do Oeste": "Desenvolvimento Moderado",
    "Pimenteiras do Oeste": "Desenvolvimento Moderado"
}

In [59]:
sinasc_raw[['QTDFILVIVO','QTDFILMORT','APGAR5','munResNome']].set_index('munResNome').groupby(IFDM).mean().round(2)

                          QTDFILVIVO  QTDFILMORT  APGAR5
munResNome
Desenvolvimento Moderado        1.05        0.27    9.16
Desenvolvimento Regular         1.32        0.27    9.24

### 5.3 PIB
C - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_PIB

In [60]:
PIB = {
    "Porto Velho": "Acima de R$ 1 Bi",
    "Guajará-Mirim": "Acima de R$ 500mi",
    "Nova Mamoré": "Acima de R$ 500mi", 
    "Alto Paraíso": "Acima de R$ 300mi",
    "Campo Novo de Rondônia": "Acima de R$ 200mi",
    "Jaru": "Acima de R$ 1 Bi",
    "Governador Jorge Teixeira": "Acima de R$ 100mi",
    "Machadinho D'Oeste": "Acima de R$ 500mi",
    "Theobroma": "Acima de R$ 100mi",
    "Vale do Anari": "Acima de R$ 100mi",
    "Ji-Paraná": "Acima de R$ 1 Bi",
    "Nova União": "Até 100mi",
    "Ouro Preto do Oeste": "Acima de R$ 500mi",
    "Presidente Médici": "Acima de R$ 300mi",
    "Seringueiras": "Acima de R$ 100mi",
    "Cacoal": "Acima de R$ 1 Bi",
    "Castanheiras": "Até 100mi",
    "Espigão D'Oeste": "Acima de R$ 500mi",
    "Pimenta Bueno": "Acima de R$ 1 Bi",
    "Santa Luzia D'Oeste": "Acima de R$ 100mi",
    "Cerejeiras": "Acima de R$ 500mi",
    "Chupinguaia": "Acima de R$ 100mi",
    "Colorado do Oeste": "Acima de R$ 300mi",
    "Pimenteiras do Oeste": "Acima de R$ 100mi"
}

In [61]:
sinasc_raw[['QTDFILMORT','QTDFILVIVO','APGAR5','munResNome']].set_index('munResNome').groupby(PIB).mean().round(2)

                   QTDFILMORT  QTDFILVIVO  APGAR5
munResNome
Acima de R$ 1 Bi         0.28        1.06    9.18
Acima de R$ 100mi        0.20        1.00    9.13
Acima de R$ 200mi        0.40        1.16    9.49
Acima de R$ 300mi        0.24        1.00    9.11
Acima de R$ 500mi        0.28        1.24    9.18
Até 100mi                0.12        0.90    9.12

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados.

É possível notar que, ao observar as condições de renda e IDH, que os munícipios possuem condições de saúde semelhantes ao avaliar índices como APGAR5, por exemplo. Indicando que, em todo o estado de RO, a questão financeira da região (ou IDH) não é uma condição determinante para a qualidade de saúde do bebê.